version: '3.8'
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: sinyal
      POSTGRES_PASSWORD: Sinyal3545
      POSTGRES_DB: sinyal_stok
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
  backend:
    build: ./backend
    ports:
      - '4000:4000'
    env_file:
      - ./backend/.env
    environment:
      PGHOST: db
      PGPORT: 5432
      PGDATABASE: sinyal_stok
      PGUSER: sinyal
      PGPASSWORD: Sinyal3545
    depends_on:
      - db
  frontend:
    build: ./frontend
    ports:
      - '5173:5173'
    depends_on:
      - backend
volumes:
  pgdata:
